/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Login;

import DAO.FuncionarioDAO;
import Model.Funcionario;
import View.Tela_Funcionario.JFramePrincipal.Tela02_Funcionario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaias
 */
public class Tela01_cadastroFuncionario extends javax.swing.JFrame {
     private boolean validaCampos = true;
    private ValidaCamposCadastro valido;
    private String confirmaSenha = null;//é usado para receber a senha e depois se´ra usado para comparar os campos
    /**
     * Creates new form Tela02_cadastro
     */
    public Tela01_cadastroFuncionario() {
        initComponents();
        //this.PainelFormulario.setVisible(false);
         this.setExtendedState(Tela01_cadastroFuncionario.MAXIMIZED_BOTH);
           getContentPane().setBackground(Color.decode("#071739"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PainelFormulario = new javax.swing.JPanel();
        jTextEmail = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jgif = new javax.swing.JLabel();
        jLabelEmailError = new javax.swing.JLabel();
        jLabelSenhaError = new javax.swing.JLabel();
        jComboCargo = new javax.swing.JComboBox<>();
        jLabelSenhaError1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordSenha = new javax.swing.JPasswordField();
        jPasswordSenha1 = new javax.swing.JPasswordField();
        jTextCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelCPFError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(667, 507));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelFormulario.setBackground(new java.awt.Color(0, 0, 0));
        PainelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Funcionário");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jLabelCargo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCargo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCargo.setText("Cargo :");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");

        jgif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imagem_2025-07-31_170538231-removebg-preview.png"))); // NOI18N

        jLabelEmailError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelEmailError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailError.setMinimumSize(new java.awt.Dimension(0, 10));
        jLabelEmailError.setPreferredSize(new java.awt.Dimension(200, 15));

        jLabelSenhaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelSenhaError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaError.setMinimumSize(new java.awt.Dimension(0, 10));
        jLabelSenhaError.setPreferredSize(new java.awt.Dimension(200, 15));

        jComboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Gerente" }));
        jComboCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboCargoFocusLost(evt);
            }
        });
        jComboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCargoActionPerformed(evt);
            }
        });

        jLabelSenhaError1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelSenhaError1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaError1.setMinimumSize(new java.awt.Dimension(0, 10));
        jLabelSenhaError1.setPreferredSize(new java.awt.Dimension(200, 15));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirmar senha");

        jPasswordSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordSenhaFocusLost(evt);
            }
        });

        jTextCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextCPFFocusLost(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF");

        jLabelCPFError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelCPFError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPFError.setMinimumSize(new java.awt.Dimension(0, 10));
        jLabelCPFError.setPreferredSize(new java.awt.Dimension(200, 15));

        javax.swing.GroupLayout PainelFormularioLayout = new javax.swing.GroupLayout(PainelFormulario);
        PainelFormulario.setLayout(PainelFormularioLayout);
        PainelFormularioLayout.setHorizontalGroup(
            PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFormularioLayout.createSequentialGroup()
                .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(PainelFormularioLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabelSenhaError1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPasswordSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelFormularioLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabelSenhaError, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelFormularioLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextCPF)
                                    .addComponent(jLabelCPFError, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextNome)
                                    .addGroup(PainelFormularioLayout.createSequentialGroup()
                                        .addComponent(jLabelCargo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addComponent(jTextEmail)
                                    .addComponent(jLabelEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jPasswordSenha))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jgif, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        PainelFormularioLayout.setVerticalGroup(
            PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFormularioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFormularioLayout.createSequentialGroup()
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(PainelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCargo)
                            .addComponent(jComboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelCPFError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSenhaError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jPasswordSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jgif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jLabelSenhaError1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 52, 0, 0);
        getContentPane().add(PainelFormulario, gridBagConstraints);

        jButton1.setText("Submeter formulário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 287, 6, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Funcionário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 182, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
       /* new SwingWorker<String, Void>() {

            @Override
            protected String doInBackground() throws Exception {
                // Aqui roda fora da interface (thread separada)
                return ValidaCamposCadastro.validarCampoEmail(jTextEmail.getText());
            }

            @Override
            protected void done() {
                switch (ValidaCamposCadastro.validarCampoEmail(jTextEmail.getText())) {
                    case "não existe" -> {
                        jLabelEmailError.setText("Email inexistente");
                        validaCampos = false;
                    }

                    case "formato errado" -> {
                        jLabelEmailError.setText("Email possui um formato errado.");
                        validaCampos = false;
                    }
                    case null -> {
                        validaCampos = false;
                        jLabelEmailError.setText("");
                    }
                    case "erro na requisição" -> jLabelEmailError.setText("Erro na request");

                    default -> throw new AssertionError();
                } // isso faz a "thread paralela" começar
            }
        }.execute();*/
    }//GEN-LAST:event_jTextEmailFocusLost

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed
public void validarConfirmaSenhaM(String senha){
    if (!confirmaSenha.equals(senha)){
       this.validaCampos=false;
       jLabelSenhaError1.setText("senha incorreta");
    }else{
     this.validaCampos=true;
      jLabelSenhaError1.setText("");
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.validarConfirmaSenhaM(jPasswordSenha1.getText());
        if (!jTextNome.getText().isBlank() && !jTextEmail.getText().isBlank()&& !jPasswordSenha.getText().isBlank() && !jTextCPF.getText().isBlank() && validaCampos) {
            FuncionarioDAO func = new FuncionarioDAO();            
            if (func.createFuncionario(new Funcionario(jTextNome.getText(),jTextCPF.getText(),jComboCargo.getSelectedItem().toString(),jTextEmail.getText(),confirmaSenha))) {
                 this.setVisible(false);
            this.getTelaFuncionario();
            }else {
            JOptionPane.showMessageDialog(this, "erro na persinstencia do banco");
        }
            
           
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos corretamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCargoActionPerformed

    private void jComboCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboCargoFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboCargoFocusLost

    private void jPasswordSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordSenhaFocusLost
        this.confirmaSenha = jPasswordSenha.getText();
    }//GEN-LAST:event_jPasswordSenhaFocusLost

    private void jTextCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCPFFocusLost
        if (jTextCPF.getText().length()!=11) {
            jLabelCPFError.setText("O cpf preciso conter exatamente 11 caracteres");
            validaCampos = false;
        }else{
             jLabelCPFError.setText("");
             validaCampos = true;
        }
    }//GEN-LAST:event_jTextCPFFocusLost
private void getTelaFuncionario() {
        Tela02_Funcionario telaFunc = new Tela02_Funcionario();
        telaFunc.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela01_cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela01_cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela01_cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela01_cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tela01_cadastroFuncionario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelFormulario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCPFError;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelEmailError;
    private javax.swing.JLabel jLabelSenhaError;
    private javax.swing.JLabel jLabelSenhaError1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JPasswordField jPasswordSenha1;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JLabel jgif;
    // End of variables declaration//GEN-END:variables
}
