/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.poo_project.Tela_Requisitante.PaineisEspecificos;

import DAO.PedidoDAO;
import DAO.ProdutoDAO;
import DTO.ProdutoDTO;
import Model.Pedido;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isaias
 */
public class Situacao extends javax.swing.JPanel {

    private ProdutoDAO prod = new ProdutoDAO();
    private HashMap<Pedido, List<ProdutoDTO>> lista = new HashMap<>();

    /**
     * Creates new form Situacao1
     */
    public Situacao() {
        lista = new PedidoDAO().requestByIdRequisitante(/*RequisitanteLogin.getId()*/5);
        initComponents();
        this.renderizaDados();
        System.out.println("tela iniciada");
         // Aplica o centralizador a todas as colunas
          DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableDefault.getColumnCount(); i++) {
            jTableDefault.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            jTableDetalhada.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) jTableDefault.getTableHeader().getDefaultRenderer();
        DefaultTableCellRenderer headerRenderer2 = (DefaultTableCellRenderer) jTableDetalhada.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        headerRenderer2.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDefault = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetalhada = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelValorTotal = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(872, 557));
        setPreferredSize(new java.awt.Dimension(872, 659));

        jTableDefault.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableDefault.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pedido", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDefaultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDefault);
        if (jTableDefault.getColumnModel().getColumnCount() > 0) {
            jTableDefault.getColumnModel().getColumn(0).setResizable(false);
            jTableDefault.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Situação dos pedidos");

        jTableDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableDetalhada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Produto", "Nome", "Quantidade desejada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDetalhada.setMinimumSize(new java.awt.Dimension(30, 80));
        jScrollPane2.setViewportView(jTableDetalhada);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText(">>");

        jButton1.setText("Cancelar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelValorTotal.setText("O valor do pedido apareça aqui...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelValorTotal)
                        .addGap(86, 86, 86))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotal)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              JOptionPane.showConfirmDialog(null,"Tem certeza que deseja cancelar o pedido:",
          "Confirme a ação",JOptionPane.YES_NO_OPTION);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDefaultMouseClicked
        // TODO add your handling code here:
        if (jTableDefault.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) jTableDetalhada.getModel();
            model.setRowCount(0);
            Integer idNaTabela = Integer.parseInt(jTableDefault.getValueAt(jTableDefault.getSelectedRow(), 0).toString());
            System.out.println("row select");
            for (Map.Entry<Pedido, List<ProdutoDTO>> entry : lista.entrySet()) {
                Pedido pedido = entry.getKey();
                List<ProdutoDTO> val = entry.getValue();
                System.out.println(pedido.getId_pedido() +"=="+ idNaTabela);
                if (pedido.getId_pedido().equals(idNaTabela)) {
                    System.out.println("if");
                    for (int i = 0; i < val.size(); i++) {
                        model.addRow(new Object[]{val.get(i).getProd().getId(),val.get(i).getProd().getNome(), val.get(i).getQuantidadeDesejada()});
                        jLabelValorTotal.setText("Valor do pedido: "+pedido.getValorTotal()); 
                    }

                }
            }

        }


    }//GEN-LAST:event_jTableDefaultMouseClicked
    private void renderizaDados() {//rendeiza pedidos feitos pela empresa
        DefaultTableModel model = (DefaultTableModel) jTableDefault.getModel();
        model.setRowCount(0);
        for (java.util.Map.Entry<Model.Pedido, java.util.List<DTO.ProdutoDTO>> entry : lista.entrySet()) {
            Pedido key = entry.getKey();
            model.addRow(new Object[]{key.getId_pedido(), key.getStatus()});

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDefault;
    private javax.swing.JTable jTableDetalhada;
    // End of variables declaration//GEN-END:variables
}
