/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poo_project.Tela_Funcionario;

import DAO.FuncionarioDAO;
import Login.FuncionarioLogin;
import com.mycompany.poo_project.Tela_Funcionario.Paineis.GerenciaPedidos;
import com.mycompany.poo_project.Tela_Funcionario.Paineis.GerenciarFuncionarios;
import com.mycompany.poo_project.Tela_Funcionario.Paineis.PedidosPendentes;
import com.mycompany.poo_project.Tela_Funcionario.Paineis.Produtos;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 *
 * @author Isaias
 */
public class Tela02_Funcionario extends javax.swing.JFrame {
    
    /**
     * Creates new form Tela02_Sistema01
     */
    public Tela02_Funcionario() {
        initComponents();
        
        btnGerenciarFuncionarios.setVisible(false);
        jLabel4.setVisible(false);
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        PedidosPendentes painelInicial = new PedidosPendentes();
        mostrarPainel(painelInicial);
        
        FuncionarioDAO dao = new FuncionarioDAO();
        ResultSet rsCargo = dao.buscarCargoFuncionario(FuncionarioLogin.getId());
        
        try {
            if (rsCargo != null && rsCargo.next()){
                String cargo = rsCargo.getString("cargo");
                if (cargo != null && cargo.equalsIgnoreCase("gerente")){
                    btnGerenciarFuncionarios.setVisible(true);
                    jLabel4.setVisible(true);
                }
            }
        } catch (SQLException e){
            System.out.println("Erro ao buscar cargo do funcionário: " + e);
        }
        
    }
     
    private void mostrarPainel(JPanel painel){
        painelPrincipal.removeAll();
        painelPrincipal.add(painel);
        painelPrincipal.revalidate();
        painelPrincipal.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelMenu = new javax.swing.JPanel();
        btnPedidosPendentes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnGerenciaPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGerenciarFuncionarios = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));

        painelMenu.setBackground(new java.awt.Color(255, 153, 0));
        painelMenu.setName(""); // NOI18N
        painelMenu.setLayout(new java.awt.GridBagLayout());

        btnPedidosPendentes.setBackground(new java.awt.Color(255, 255, 255));
        btnPedidosPendentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/feedback.png"))); // NOI18N
        btnPedidosPendentes.setMaximumSize(null);
        btnPedidosPendentes.setMinimumSize(null);
        btnPedidosPendentes.setPreferredSize(null);
        btnPedidosPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosPendentesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 10);
        painelMenu.add(btnPedidosPendentes, gridBagConstraints);

        btnProdutos.setBackground(new java.awt.Color(255, 255, 255));
        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/product.png"))); // NOI18N
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 10);
        painelMenu.add(btnProdutos, gridBagConstraints);

        btnGerenciaPedidos.setBackground(new java.awt.Color(255, 255, 255));
        btnGerenciaPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/compare.png"))); // NOI18N
        btnGerenciaPedidos.setMaximumSize(null);
        btnGerenciaPedidos.setMinimumSize(null);
        btnGerenciaPedidos.setPreferredSize(null);
        btnGerenciaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciaPedidosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 10);
        painelMenu.add(btnGerenciaPedidos, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aprovar Pedidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 10);
        painelMenu.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gerenciar Produtos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 10);
        painelMenu.add(jLabel2, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gerenciar Pedidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 10);
        painelMenu.add(jLabel3, gridBagConstraints);

        btnGerenciarFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        btnGerenciarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/satisfied-customer.png"))); // NOI18N
        btnGerenciarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarFuncionariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 10);
        painelMenu.add(btnGerenciarFuncionarios, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gerenciar Funcionários");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 10);
        painelMenu.add(jLabel4, gridBagConstraints);

        painelPrincipal.setBackground(new java.awt.Color(7, 23, 57));
        painelPrincipal.setPreferredSize(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosPendentesActionPerformed
        // TODO add your handling code here:
        PedidosPendentes painel = new PedidosPendentes();
        mostrarPainel(painel);
    }//GEN-LAST:event_btnPedidosPendentesActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        Produtos painel = new Produtos();
        mostrarPainel(painel);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnGerenciaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciaPedidosActionPerformed
        // TODO add your handling code here:
        GerenciaPedidos painel = new GerenciaPedidos();
        mostrarPainel(painel);
    }//GEN-LAST:event_btnGerenciaPedidosActionPerformed

    private void btnGerenciarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarFuncionariosActionPerformed
        // TODO add your handling code here:
        GerenciarFuncionarios painel = new GerenciarFuncionarios();
        mostrarPainel(painel);
    }//GEN-LAST:event_btnGerenciarFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela02_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela02_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela02_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela02_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela02_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerenciaPedidos;
    private javax.swing.JButton btnGerenciarFuncionarios;
    private javax.swing.JButton btnPedidosPendentes;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
