/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Tela_Funcionario.Paineis;

import DAO.PedidoDAO;
import Model.Pedido;
import Model.StatusPedido;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cliente
 */
public class GerenciaPedidos extends javax.swing.JPanel {

    /**
     * Creates new form GerenciaPedidos
     */
    public GerenciaPedidos() {
        initComponents();
        configurarTabela();
        carregarDados();
    }
    
    private void configurarTabela() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Selecionar", "ID", "Requisitante", "Data", "Total", "Status"}
        ) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? Boolean.class : String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0; // Só a coluna de checkbox pode ser editada
            }
        };
        tabelaPedidos.setModel(modelo);
    }
    
    private void carregarDados() {
        DefaultTableModel model = (DefaultTableModel) tabelaPedidos.getModel();
        model.setRowCount(0); // Limpar a tabela

        List<Pedido> pedidos = new PedidoDAO().readPedido();

        for (Pedido p : pedidos) {
            model.addRow(new Object[]{
                false, // checkbox desmarcado
                p.getId_pedido(),
                p.getId_requisitante(),
                p.getData_pedido().toString(),
                p.getValorTotal(),
                p.getStatus()
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnVerProdutos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 23, 57));
        setMinimumSize(new java.awt.Dimension(872, 557));
        setPreferredSize(new java.awt.Dimension(825, 659));

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Seleção", "ID", "Requisitante", "Data", "Total", "Status"
            }
        ));
        tabelaPedidos.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tabelaPedidos);

        btnAtualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar Status");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnVerProdutos.setBackground(new java.awt.Color(0, 0, 0));
        btnVerProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerProdutos.setText("Ver Produtos");
        btnVerProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProdutosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerProdutos)
                .addGap(57, 57, 57)
                .addComponent(btnAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAtualizar)
                    .addComponent(btnVerProdutos))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelaPedidos.getModel();

        List<Integer> pedidosSelecionados = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean selecionado = (Boolean) model.getValueAt(i, 0);
            if (Boolean.TRUE.equals(selecionado)) {
                Integer idPedido = (Integer) model.getValueAt(i, 1);
                pedidosSelecionados.add(idPedido);
            }
        }

        if (pedidosSelecionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum pedido selecionado.");
            return;
        }

        StatusPedido novoStatus = (StatusPedido) JOptionPane.showInputDialog(
            this,
            "Escolha o novo status:",
            "Atualizar Status",
            JOptionPane.QUESTION_MESSAGE,
            null,
            StatusPedido.values(),
            StatusPedido.Pendente
        );

        if (novoStatus == null) return; 

        PedidoDAO dao = new PedidoDAO();
        for (Integer id : pedidosSelecionados) {
            Pedido p = new Pedido();
            p.setStatus(novoStatus);
            dao.updatePedido(p, id); 
        }

        JOptionPane.showMessageDialog(this, "Status atualizado com sucesso.");
        carregarDados(); 
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnVerProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProdutosActionPerformed
        // TODO add your handling code here:
        int countSelected = 0;
        int idPedido = -1;

        for (int i = 0; i < tabelaPedidos.getRowCount(); i++) { 
            Boolean isSelected = (Boolean) tabelaPedidos.getValueAt(i, 0); 
            if (isSelected != null && isSelected) {
                countSelected++;
                idPedido = (int) tabelaPedidos.getValueAt(i, 1); 
            }
        }

        if (countSelected == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido.");
            return;
        }

        if (countSelected > 1) {
            JOptionPane.showMessageDialog(this, "Selecione apenas um pedido por vez.");
            return;
        }

        ProdutosPedido painelProdutos = new ProdutosPedido(idPedido);

        JDialog dialog = new JDialog();
        dialog.setTitle("Produtos do Pedido " + idPedido);
        dialog.setContentPane(painelProdutos);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE); // para fechar corretamente
        dialog.pack();
        dialog.setLocationRelativeTo(this); 
        dialog.setModal(true);              
        dialog.setVisible(true);            

    }//GEN-LAST:event_btnVerProdutosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnVerProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables
}
