/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Tela_Funcionario.Paineis;

import Controller.CapturaLogin.FuncionarioLogin;
import DAO.PedidoDAO;
import Model.Pedido;
import Model.StatusPedido;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cliente
 */
public class PedidosPendentes extends javax.swing.JPanel {

    /**
     * Creates new form PedidosPendentes
     */
    public PedidosPendentes() {
        initComponents();
        
        lblMensagemVazia.setVisible(false);

        DefaultTableModel modelo = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Seleção", "ID", "Requisitante", "Data", "Total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                Boolean.class, Integer.class, String.class, java.sql.Date.class, java.math.BigDecimal.class, String.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0; // apenas checkbox editável
            }
        };

        tabelaPedidosPendentes.setModel(modelo);

        carregarDados();
    }
    
     private void carregarDados() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPedidosPendentes.getModel();
        modelo.setRowCount(0); 
        
        PedidoDAO dao = new PedidoDAO();
        List<Pedido> pedidos = dao.readPedido();

        for (Pedido p : pedidos) {
            if (p.getStatus() == StatusPedido.Pendente.name()) {
                modelo.addRow(new Object[]{
                    false,
                    p.getId_pedido(),
                    p.getId_requisitante(),
                    java.sql.Date.valueOf(p.getData_pedido()),
                    p.getValorTotal(),
                    p.getStatus().toString()
                });
            }
        }
        
        lblMensagemVazia.setVisible(modelo.getRowCount() == 0);
        
    }
    
    
    private void atualizarStatusPedidos(List<Integer>ids, StatusPedido novoStatus){
        PedidoDAO pdao = new PedidoDAO();
        int idFuncionario = FuncionarioLogin.getId();
        
        for (int id : ids) {
            Pedido p = new Pedido();
            p.setId_requisitante(2);
            p.setStatus(novoStatus);
            p.setId_funcionario(idFuncionario);
            pdao.updatePedido(p,id);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidosPendentes = new javax.swing.JTable();
        btnVerProdutos = new javax.swing.JButton();
        btnAceitar = new javax.swing.JButton();
        btnRecusar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMensagemVazia = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 23, 57));
        setMinimumSize(new java.awt.Dimension(872, 557));
        setPreferredSize(new java.awt.Dimension(825, 659));

        tabelaPedidosPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Seleção", "ID", "Requisitante", "Data", "Total", "Status"
            }
        ));
        tabelaPedidosPendentes.setRowSelectionAllowed(false);
        tabelaPedidosPendentes.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tabelaPedidosPendentes);

        btnVerProdutos.setBackground(new java.awt.Color(0, 0, 0));
        btnVerProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerProdutos.setText("Ver Produtos");
        btnVerProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProdutosActionPerformed(evt);
            }
        });

        btnAceitar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceitar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceitar.setText("Aceitar");
        btnAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarActionPerformed(evt);
            }
        });

        btnRecusar.setBackground(new java.awt.Color(0, 0, 0));
        btnRecusar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecusar.setText("Recusar");
        btnRecusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecusarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedidos Pendentes");
        jLabel1.setMaximumSize(new java.awt.Dimension(289, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(289, 48));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(659, 48));

        lblMensagemVazia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMensagemVazia.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagemVazia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMensagemVazia.setText("Não há pedidos pendentes no momento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblMensagemVazia, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(btnVerProdutos)
                        .addGap(74, 74, 74)
                        .addComponent(btnAceitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecusar))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensagemVazia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerProdutos)
                    .addComponent(btnAceitar)
                    .addComponent(btnRecusar))
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProdutosActionPerformed
        // TODO add your handling code here:
        int countSelected = 0;
        int idPedido = -1;

        for (int i = 0; i < tabelaPedidosPendentes.getRowCount(); i++) {
            Boolean isSelected = (Boolean) tabelaPedidosPendentes.getValueAt(i, 0);
            if (isSelected != null && isSelected) {
                countSelected++;
                idPedido = (int) tabelaPedidosPendentes.getValueAt(i, 1);
            }
        }

        if (countSelected == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido.");
            return;
        }

        if (countSelected > 1) {
            JOptionPane.showMessageDialog(this, "Selecione apenas um pedido por vez.");
            return;
        }

        // Aqui está a forma correta de exibir o JPanel como janela modal
        ProdutosPedido painelProdutos = new ProdutosPedido(idPedido);

        JDialog dialog = new JDialog();
        dialog.setTitle("Produtos do Pedido");
        dialog.setContentPane(painelProdutos);
        dialog.pack();
        dialog.setLocationRelativeTo(this); 
        dialog.setModal(true);              
        dialog.setVisible(true);            

    }//GEN-LAST:event_btnVerProdutosActionPerformed

    private void btnAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarActionPerformed
        // TODO add your handling code here:
        List<Integer> pedidosSelecionados = new ArrayList<>();

        for (int i = 0; i < tabelaPedidosPendentes.getRowCount(); i++) {
            Boolean isSelected = (Boolean) tabelaPedidosPendentes.getValueAt(i, 0);
            if (isSelected != null && isSelected) {
                int idPedido = (int) tabelaPedidosPendentes.getValueAt(i, 1);
                pedidosSelecionados.add(idPedido);
            }
        }

        if (pedidosSelecionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione pelo menos um pedido.");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(this, "Deseja aceitar os pedidos selecionados?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            atualizarStatusPedidos(pedidosSelecionados, StatusPedido.Aprovado);
            JOptionPane.showMessageDialog(this, "Pedidos aceitos.");
            carregarDados();
        }

    }//GEN-LAST:event_btnAceitarActionPerformed

    private void btnRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecusarActionPerformed
        // TODO add your handling code here:
        List<Integer> pedidosSelecionados = new ArrayList<>();

        for (int i = 0; i < tabelaPedidosPendentes.getRowCount(); i++) {
            Boolean isSelected = (Boolean) tabelaPedidosPendentes.getValueAt(i, 0);
            if (isSelected != null && isSelected) {
                int idPedido = (int) tabelaPedidosPendentes.getValueAt(i, 1);
                pedidosSelecionados.add(idPedido);
            }
        }

        if (pedidosSelecionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione pelo menos um pedido.");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(this, "Deseja recusar os pedidos selecionados?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            atualizarStatusPedidos(pedidosSelecionados, StatusPedido.Recusado);
            JOptionPane.showMessageDialog(this, "Pedidos recusados.");
            carregarDados();
        }
    }//GEN-LAST:event_btnRecusarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JButton btnRecusar;
    private javax.swing.JButton btnVerProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagemVazia;
    private javax.swing.JTable tabelaPedidosPendentes;
    // End of variables declaration//GEN-END:variables
}
