/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poo_project.Login_cadastro;

import DAO.EmpresaDAO;
import DAO.FuncionarioDAO;
import Login.FuncionarioLogin;
import Login.RequisitanteLogin;
import com.mycompany.poo_project.Login_cadastro.Tela01_cadastroEmpresa;
import com.mycompany.poo_project.Tela_Funcionario.Tela02_Funcionario;
import com.mycompany.poo_project.Tela_Requisitante.Tela02_Requisitante;
import java.awt.Color;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaias
 */
public class Tela01_Login extends javax.swing.JFrame {

    FuncionarioDAO funcDAO = new FuncionarioDAO();
    EmpresaDAO empDAO = new EmpresaDAO();

    /**
     * Creates new form Tela01_Login
     */
    public Tela01_Login() {
        /*URL url = getClass().getResource("../imgs/imgLogin.png");
System.out.println("URL da imagem: " + url);*/

        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
      getContentPane().setBackground(Color.decode("#071739")); // cor pêssego
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelImg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textEmail = new javax.swing.JLabel();
        TextLogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        inputSenha = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        textSenha = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jframe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabelImg.setBackground(new java.awt.Color(51, 255, 51));
        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/teste.png"))); // NOI18N
        jLabelImg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(255, 102, 51)));
        jLabelImg.setIconTextGap(0);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(255, 102, 51)));

        textEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        TextLogin.setBackground(new java.awt.Color(255, 255, 255));
        TextLogin.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        TextLogin.setForeground(new java.awt.Color(255, 255, 255));
        TextLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLogin.setText("Login");

        jButton1.setText("Cadastrar-se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        inputSenha.setForeground(new java.awt.Color(124, 124, 124));
        inputSenha.setText("Senha");
        inputSenha.setDoubleBuffered(true);
        inputSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputSenhaFocusLost(evt);
            }
        });

        inputEmail.setForeground(new java.awt.Color(124, 124, 124));
        inputEmail.setText("Email");
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        textSenha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputEmail)
                                .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButtonEntrar))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(TextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(TextLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelImg)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel2, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed

        /*
        System.out.println("senha = "+inputSenha.getText());
        System.out.println("email = "+inputEmail.getText());*/
        if ((!inputEmail.getText().isBlank() && !inputEmail.getText().contains("email")) && (!inputSenha.getText().isBlank() && !inputSenha.getText().contains("Senha"))) {
            if (inputEmail.getText().contains("Emp")) {
                //this.Login("funcionario");
                if (!this.Login("funcionario")) {
                    JOptionPane.showMessageDialog(null,
                            "Campo de senha ou email incorreto", "alerta", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Login inválido ou sem retorno");
                };
            } else {
                if (!this.Login("empresa")) {
                    JOptionPane.showMessageDialog(null,
                            "Campo de senha ou email incorreto", "alerta", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Login inválido ou sem retorno");
                };
            }

        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "alerta",
                    JOptionPane.ERROR_MESSAGE);
            //System.out.println("else");

        }

    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             
Object[] itens = { "Funcionario","Empresa"};
      Object selectedValue = JOptionPane.showInputDialog(null,
         "Escolha um item", "Opçao",
              JOptionPane.INFORMATION_MESSAGE, null,
                  itens, itens [0]); 
        if (selectedValue.equals("Funcionario")) {
            this.getTelaCadastroFuncionario();
        }else{
        this.getTelaCadastro();
        }
//
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        // TODO add your handling code here:
        if (inputEmail.getText().isBlank()) {
            inputEmail.setText("Email");
            inputEmail.setForeground(new Color(124, 124, 124));
            textEmail.setText("");
        }
    }//GEN-LAST:event_inputEmailFocusLost

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        if (inputEmail.getText().equals("Email")) {
            inputEmail.setText("");
            inputEmail.setForeground(Color.BLACK);
            textEmail.setText("Email");
            textEmail.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSenhaFocusLost
        // TODO add your handling code here:
        if (inputSenha.getText().isBlank()) {
            inputSenha.setText("Senha");
            inputSenha.setForeground(new Color(124, 124, 124));
            textSenha.setText("");
        }
    }//GEN-LAST:event_inputSenhaFocusLost

    private void inputSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSenhaFocusGained
        if (inputSenha.getText().equals("Senha")) {
            inputSenha.setText("");
            inputSenha.setForeground(Color.BLACK);
            textSenha.setText("Senha");
            textSenha.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_inputSenhaFocusGained

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void getTelaCadastro() {
        Tela01_cadastroEmpresa cadastro = new Tela01_cadastroEmpresa();
        cadastro.setVisible(true);
    }
    private void getTelaCadastroFuncionario() {
        Tela01_cadastroFuncionario cadastro = new Tela01_cadastroFuncionario ();
        cadastro.setVisible(true);
    }

    private void getTelaFuncionario() {
        Tela02_Funcionario telaFunc = new Tela02_Funcionario();
        telaFunc.setVisible(true);
    }

    private void getTela_Requisitante() {
        Tela02_Requisitante telaReq = new Tela02_Requisitante();
        telaReq.setVisible(true);
        //
    }

    private boolean Login(String userTipo) {
        ResultSet rs = null;
        if (userTipo.equals("funcionario")) {
            try {
                rs = funcDAO.validacaoLoginFuncionario(inputEmail.getText(), inputSenha.getText());
                if (rs != null && rs.next()) {
                    int idFuncionario = rs.getInt("id_func");
                    int idEmpresa = rs.getInt("id_empresa_fk");
                    new FuncionarioLogin(idFuncionario, idEmpresa);
                    this.getTelaFuncionario();
                    return true;
                }
            } catch (SQLException e) {
                System.out.println("ERRO NA REQUISIÇÃO DO LOGIN: " + e);
            }

        } else if (userTipo == "empresa") {
            try {
                rs = empDAO.validacaoLoginEmpresa(inputEmail.getText(), inputSenha.getText());
                System.out.println("entrou no try");
                if (rs != null && rs.next()) { // move para o primeiro resultado
                    // String tipo = ; // lê o valor do campo
                    new RequisitanteLogin(rs.getInt("id_empresa"), rs.getString("nome_empresa"));
                    this.getTela_Requisitante();
                    return true;
                    /*if (tipo.contains("fornecedor")) {
                       
                        new FornecedorLogin(rs.getInt("id_empresa"),  rs.getString("nome_empresa"), tipo,  this.inputSenha.getText() );
                        this.getTelaFuncionario();
                        
                    } else{ 
                        
                        
                    }*/

                }

            } catch (SQLException e) {
                System.out.println("ERRO NA REQUISIÇÃO DO LOGIN: " + e);
            }

        }
        return false;
    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tela01_Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextLogin;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel textEmail;
    private javax.swing.JLabel textSenha;
    // End of variables declaration//GEN-END:variables
}
