/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poo_project.Tela_Requisitante;

import com.mycompany.poo_project.Tela_Requisitante.PaineisEspecificos.Carrinho;
import com.mycompany.poo_project.Tela_Requisitante.PaineisEspecificos.Situacao;
import com.mycompany.poo_project.Tela_Requisitante.PaineisEspecificos.Visualizador;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Isaias
 * @creditos img de buttons : https://www.flaticon.com/br/autores/hazicon
 * https://www.flaticon.com/br/autores/inipagistudio
 */
public class Tela02_Requisitante extends javax.swing.JFrame {

    /**
     * Creates new form Tela02_Sistema01
     */
    public Tela02_Requisitante() {
        initComponents();
        Visualizador tela1 = new Visualizador();
        tela1.setSize(872, 557);
        tela1.setLocation(0, 0);
        this.getContentPane().setBackground(Color.decode("#071739"));//POG MASTER PLUS ULTRA
        BProdutos.setHorizontalAlignment(SwingConstants.CENTER);
BProdutos.setVerticalAlignment(SwingConstants.CENTER);

        content.removeAll();
        content.add(tela1, BorderLayout.CENTER);
        content.repaint();
        /*ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/vista-lateral-vazia-do-carrinho-de-compras_1")); // Load image from resources
        BProdutos.setIcon(icon); // Set image as icon

        BProdutos.setText(""); // Remove text
        BProdutos.setBorderPainted(false); // Remove border (opcional)
        BProdutos.setContentAreaFilled(false); // Remove fundo (opcional)
        BProdutos.setFocusPainted(false); // Remove efeito de foco (opcional)*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BCarrinho = new javax.swing.JButton();
        BProdutos = new javax.swing.JButton();
        BSituacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        BCarrinho.setBackground(new java.awt.Color(255, 255, 255));
        BCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/carrinho-vazio.png"))); // NOI18N
        BCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCarrinhoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 10, 0, 10);
        jPanel1.add(BCarrinho, gridBagConstraints);

        BProdutos.setBackground(new java.awt.Color(255, 255, 255));
        BProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/caixa-de-armazenamento.png"))); // NOI18N
        BProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProdutosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 10, 0, 10);
        jPanel1.add(BProdutos, gridBagConstraints);

        BSituacao.setBackground(new java.awt.Color(255, 255, 255));
        BSituacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/descricao-do-produto.png"))); // NOI18N
        BSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSituacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 10, 0, 10);
        jPanel1.add(BSituacao, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visualizar Produtos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carrinho");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Situação dos Pedidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 45, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        content.setBackground(new java.awt.Color(7, 23, 57));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        content.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSituacaoActionPerformed
        // TODO add your handling code here:
        Situacao s = new Situacao();
        this.renderizaJPanel(s);
    }//GEN-LAST:event_BSituacaoActionPerformed

    private void BProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProdutosActionPerformed
        // TODO add your handling code here:
        Visualizador v = new Visualizador();
        this.renderizaJPanel(v);
    }//GEN-LAST:event_BProdutosActionPerformed

    private void BCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCarrinhoActionPerformed
        // TODO add your handling code here:
        Carrinho c = new Carrinho();
        this.renderizaJPanel(c);
    }//GEN-LAST:event_BCarrinhoActionPerformed

    private void renderizaJPanel(JPanel p) {
        p.setSize(872, 557);        // Define o tamanho do painel novo
        p.setLocation(0, 0);        // Define a posição inicial

        content.removeAll();        // Remove o conteúdo anterior
        content.add(p, BorderLayout.CENTER); // Adiciona o novo painel

        content.revalidate();       // REORGANIZA os componentes com base no layout
        content.repaint();          //️ REDESENHA a interface com os componentes atualizados
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela02_Requisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela02_Requisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela02_Requisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela02_Requisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela02_Requisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCarrinho;
    private javax.swing.JButton BProdutos;
    private javax.swing.JButton BSituacao;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
